### ISSUE TITLE
Cropping without shifting the subtitles

### ISSUE THREAD

**Issue by FoxInFlame** [MonoS/SupMover#1]
Thanks for this wonderful tool.

Could you perhaps add an option to crop without shifting the images? I removed black letterbox bars from a video, and I want to do the same for the subtitles. In picture:

![image worth thousand words](https://i.imgur.com/JOwISRk.png)

I have a feeling removing the subtraction from [line 395](https://github.com/MonoS/SupMover/blob/master/main.cpp#L395) would do it, but as I'm not experienced with C++ nor do I have the necessary environment to build and compile myself, I thought I'd just ask.

**Comment by MonoS** [comment]
Hi, i think my tool already does what you are asking for, i'm forced to shift the image because when cropping the video we remove the top part of the image shifting the center part, the picture data will stay at the same relative position except when it overlaps the cropped area, in that case an additional fix is required or the subtitle picture data will go outside the new video area.

Try it and please, remember to check the resulting file with a video player, especially when it tells you to check, as i've noticed that sometimes some subtitle may became invisible if they use some more arcane sup capabilities.

Also i've uploaded a new version, please download that :)

**Comment by FoxInFlame** [comment]
Oh awesome! It must've been the new bugfix that fixed it. I had nothing in my console output before (I assumed it produced no output unless it had some verbosity setting turned on), but with 2.0.1 I got several "multiple windows/compositions" warnings, and it properly cropped and fitted itself.

This is a wonderful tool, thank you very much! I was originally looking at BDSup2Sub, but my subtitles contain sing-along sections (changing colour per character) which became invisible with that tool, and plus the repo wasn't updated for 8-9 years. SupMover's doing exactly what I wanted to.

**Comment by MonoS** [comment]
Yeah, before it was checking only on the delay to apply any changes (due to the previous logic) so if you would not set any it won't do any changes, i didn't noticed because i've always tested it with a delay.

I've also used BDSup2Sub, all three version, and it doesn't work, it try to recreate the resulting picture (if you don't know, sup file are like png with some timing in them) and doing that it will recompress the image changing the palette, also sometimes, as it happened to you, it make some pic disappear without warning, well my tools sometimes does the same, but i try to warn the user...
