### ISSUE TITLE
Error parsing cutMerge list

### ISSUE THREAD

**Issue by cemoon95** [MonoS/SupMover#10]
When I try to run it with the command
`SupMover 01.sup 01_edit.sup add_zero cut_merge list "[1-2182] [2182-30048] [37265-51086] [51088-51207] [51210-71970] [71969-77015] [76999-77759]" format secut timemode frame 23.976 fixmode cut`

it throws an "Error parsing input" error.
The cropping etc. functions work fine, so it's possible I'm interpreting how the cut_merge syntax is supposed to be written out; if so I'd appreciate help on how I'm supposed to write it.

**Comment by MonoS** [comment]
Hi cemoon95, the problem is in the section format, the pattern `[frame-frame] [frame-frame]` is not supported, the secut format expect the list in pattern `frame-frame;frame-frame`, something like this will work
`add_zero cut_merge list "1-2182;2182-30048;37265-51086;51088-51207;51210-71970;71969-77015;76999-77759" format secut timemode frame 23.976 fixmode cut`

Please pay attention the cut_merge functionality is currently non functional as there is a serious bug I've yet to solve, it will only works if there are no consecutive lines in the script, for example something like this won't work
![image](https://github.com/MonoS/SupMover/assets/801011/42d65ee8-2828-4c97-b738-9f165c3145e9)
